version: '3.4'

services:
  searchapi:
    image: omsearchapi
    build:
      context: .
      dockerfile: SearchAPI/Dockerfile

  nsearchapi:
    image: nsearchapi
    build:
      context: .
      dockerfile: NSearchAPI/Dockerfile

  redis:
    container_name: redis
    image: 'redislabs/redisearch:latest'
    ports:
      - '6379:6379'
